name: seqdbs
channels:
 - conda-forge
 - bioconda
dependencies:
 - snakemake-minimal=8
 - snakemake-storage-plugin-http
 - biopython
 - prinseq
 - last
 - wget
 - curl
 - diamond
 - bwa
 - tantan
 - prodigal
 - pandas
